config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'

  ##get 'static_pages/top'
  root 'static_pages#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  
  ## ログイン機能(6.1 最初に実装するnewアクションを指定して生成)
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  ## 9.3.1 モーダルウインドウを表示  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      ## 11.1 勤怠編集ページの作成し、ルーティングを設定
      get 'attendances/edit_one_month'
      ## 11.1.4 勤怠編集ページの更新ボタン作成
      patch 'attendances/update_one_month'
    end
    ##10.5.1 ルーティングを設定/出勤登録ボタン
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  ##10.1.1 【1対多】の関連付け
  has_many :attendances, dependent: :destroy
  ## 7.1.2 rememberメソッドを作る
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  ## 9.1.1 「department（所属）」カラムのバリデーションを設定
  validates :department, length: { in: 2..30 }, allow_blank: true
  ## 9.2.1 勤怠基本情報のバリデーションを設定
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  ## 8.1.4 パスワードはスルーして更新できるようにする
  ##validates :password, presence: true, length: { minimum: 6 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  ## 7.1.1 ランダムな文字列を作る
  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  ## 7.1.1 ランダムな文字列を作る
  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  ## 7.1.2 rememberメソッドを作る
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  ## 7.1.3 ログイン状態の永続的保持
    # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    ## 7.2 ふたつの小さなバグを直す
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  ## 7.1.4 ユーザーの記憶を忘れる
  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ## 8.2.2 正しいユーザーであることを要求する
  ##before_action :set_user, only: [:show, :edit, :update]
  ## 8.5.2 destroyアクション
  ## 9.3.1 モーダルウインドウを表示(, :edit_basic_info, :update_basic_infoの追加)
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  ## 8.2.1 ユーザーにログインを要求する
  ##before_action :logged_in_user, only: [:show, :edit, :update]
  ## 8.4 全てのユーザーを表示するページ
  ##before_action :logged_in_user, only: [:index, :show, :edit, :update]
  ## 8.5.2 destroyアクション
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  ## 8.2.2 正しいユーザーであることを要求する
  before_action :correct_user, only: [:edit, :update]
  ## 8.5.2 destroyアクション
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  ##10.3 "ユーザー"の月日を一覧表示
  before_action :set_one_month, only: :show
  
  ## 8.4 全てのユーザーを表示するページ
  def index
    ##@users = User.all
    ## 8.4.2 ページネーションを使おう
    @users = User.paginate(page: params[:page])
  end
  
  ## 5.2 Usersリソース(findメソッドを使ってユーザーオブジェクトを取得してインスタンス変数を代入)
  def show
  ## 9.3.1 モーダルウインドウを表示  
    ##@user = User.find(params[:id])
    ##10.2 月日を一覧表示しよう(勤怠情報表示ページ)
    ##10.3 "ユーザー"の月日を一覧表示
    ##@first_day = Date.current.beginning_of_month
    ##@last_day = @first_day.end_of_month
    ##<!-- 10.7 出勤日数を表示 -->
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
  def new
    @user = User.new # 5.5 ユーザーオブジェクトを生成し、インスタンス変数に代入します。
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      ## 6.5 ユーザー登録と同時にログインする
      log_in @user # 保存成功後、ログインします。
      ## 5.5.6 サクセスメッセージを表示
      flash[:success] = '新規作成に成功しました。'
      ## 5.5.5 ユーザーを保存
      redirect_to @user
    else
      render :new
    end
  end
  
  ## 8.1 ユーザー編集ページを作る
  def edit
    ## 9.3.1 モーダルウインドウを表示  
    ##@user = User.find(params[:id])
  end
  
  ## 8.1.2 更新に失敗した場合の処理
  def update
    ## 9.3.1 モーダルウインドウを表示  
    ##@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # 更新に成功した場合の処理を記述します。
      ## 8.1.3 更新に成功した場合の処理
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end
  
  ## 8.5.2 destroyアクション
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  ## 9.3.1 モーダルウインドウを表示
  def edit_basic_info
  end

  ## 9.3.1 モーダルウインドウを表示
  def update_basic_info
    ## 9.3.2 更新アクションを完成させよう
    if @user.update_attributes(basic_info_params)
      # 更新成功時の処理
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      # 更新失敗時の処理
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  
  
  ## 5.5.3 Strong Parameters  
  private

    def user_params
      ## 9.1.3 StrongParameters（user_paramsにdepartment属性を加えて対応）
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
  
    ## 9.3.2 更新アクションを完成
    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
  
  
  
  
  ## 11.1.3 勤怠情報ページのアクション作成でset_userアクションをapplicationコントローラーへ引越し
  ## 8.2.1 ユーザーにログインを要求する
  # beforeフィルター
  
     ## 8.5.2 destroyアクション
    # paramsハッシュからユーザーを取得します。
    ##def set_user
      ##@user = User.find(params[:id])
    ##end

    # ログイン済みのユーザーか確認します。
    ##def logged_in_user
      ##unless logged_in?
        ## 8.5.2 destroyアクション
        ##store_location
        ##flash[:danger] = "ログインしてください。"
        ##redirect_to login_url
      ##end
    ##end
  
  ## 8.2.2 正しいユーザーであることを要求する
  # アクセスしたユーザーが現在ログインしているユーザーか確認します。
    ##def correct_user
      ##@user = User.find(params[:id])
      ## 8.2.2 正しいユーザーであることを要求する
      #redirect_to(root_url) unless @user == current_user
      ##redirect_to(root_url) unless current_user?(@user)
    ##end
  
  ## 8.5.2 destroyアクション
  # システム管理権限所有かどうか判定します。
    ##def admin_user
      ##redirect_to root_url unless current_user.admin?
    ##end

end

app/helpers/users_helper.rb
module UsersHelper
  ## 9.2.3 基本表示用ヘルパーを作る
  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<!-- 9.3.1 モーダルウインドウを表示 -->
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <!-- 9.1.2 createとupdateに対応 -->
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <!-- <%= f.label :password_confirmation, "Confirmation", class: "label-#{yield(:class_text)}" %> -->
  <!-- 8x.6 Confirmationの修正 -->
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<!-- 8.1.1 少し発展的なパーシャルの使い方 -->
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <!-- 8.1.1 少し発展的なパーシャルの使い方 -->
    <%= render 'form' %>
    <!-- <%= form_with(model: @user, local: true) do |f| %> -->
      <!-- <%= render 'shared/error_messages' %> -->

      <!-- <%= f.label :name, class: "label-user--edit" %> -->
      <!-- <%= f.text_field :name, class: "form-control" %> -->

      <!-- <%= f.label :email, class: "label-user--edit" %> -->
      <!-- <%= f.email_field :email, class: "form-control" %> -->

      <!-- <%= f.label :password, class: "label-user--edit" %> -->
      <!-- <%= f.password_field :password, class: "form-control" %> -->

      <!-- <%= f.label :password_confirmation, "Confirmation", class: "label-user--edit" %> -->
      <!-- <%= f.password_field :password_confirmation, class: "form-control" %> -->

      <!-- <%= f.submit "更新", class: "btn btn-primary btn-block btn-user--edit" %> -->
    <!-- <% end %> -->
  </div>
</div>

app/views/users/edit_basic_info.js.erb
<!-- 9.3.1 パーシャルをレンダリング -->
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
<!-- 9.3.1 モーダルウインドウとして表示を実行 -->
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<!-- 8.4 全てのユーザーを表示するページ -->
<% provide(:title, 'All Users') %>
<h1>ユーザー一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <!-- 8.4.2 ページネーションを使おう -->
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <!-- 9.3.1 モーダルウインドウを表示(管理者権限の明確化) -->
        <th class="center"><%= User.human_attribute_name :department %></th>
        <% if current_user.admin? %>
          <th class="center"><%= User.human_attribute_name :basic_time %></th>
           <th class="center"><%= User.human_attribute_name :work_time %></th>
        <% end %>
        <!-- 8.5.2 destroyアクション -->
        <th></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td>
          <!-- 9.3.1 モーダルウインドウを表示(管理者権限の明確化) -->
          <% if current_user.admin? %>
            <%= link_to user.name, user %>
          <% else %>
            <%= user.name %>
          <% end %>
        </td>
        <!-- 8.5.2 destroyアクション -->
        <!-- 9.3.1 モーダルウインドウを表示(管理者権限の明確化) -->
        <td class="center"><%= user.department.present? ? user.department : "未所属" %></td>
        <% if current_user.admin? %>
          <td class="center"><%= format_basic_info(user.basic_time) %></td>
          <td class="center"><%= format_basic_info(user.work_time) %></td>
        <% end %>
        <td class="center">
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "基本情報編集", edit_basic_info_user_path(user), remote: true, class: "btn btn-success" %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <!-- 8.4.2 ページネーションを使おう -->
  <%= will_paginate %>
</div>

<!-- 9.3.1 モーダルウインドウを表示(管理者権限の明確化) -->
<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<!-- <h1>Users#new</h1> -->
<!-- <p>Find me in app/views/users/new.html.erb</p> -->

<!-- 3.5.3 ビューの作成 -->
<% provide(:title, 'Sign up') %>
<!-- 8.1.1 少し発展的なパーシャルの使い方 -->
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<!-- 5.5 ユーザー登録ページを作ろう -->
<!-- <p>このページでは必要な項目を入力して、ユーザーを新規作成します。</p> -->
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <!-- 8.1.1 少し発展的なパーシャルの使い方 -->
    <%= render 'form' %>
    <!-- <%= form_with(model: @user, local: true) do |f| %> -->
      <!-- 5.5.4 登録失敗時のエラーメッセージを表示しよう -->
      <!-- <%= render 'shared/error_messages' %> -->
      <!-- <%= f.label :name, class: "label-signup" %> -->
      <!-- <%= f.text_field :name, class: "form-control" %> -->

      <!-- <%= f.label :email, class: "label-signup" %> -->
      <!-- <%= f.email_field :email, class: "form-control" %> -->

      <!-- <%= f.label :password, class: "label-signup" %> -->
      <!-- <%= f.password_field :password, class: "form-control" %> -->

      <!-- <%= f.label :password_confirmation, "Confirmation", class: "label-signup" %> -->
      <!-- <%= f.password_field :password_confirmation, class: "form-control" %> -->

      <!-- <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-signup" %> -->
    <!-- <% end %> -->
  </div>
</div>

app/views/users/show.html.10-4未完成.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <!-- 10.2 月日の一覧表示 -->
      <!--  <td>時間管理表</td> -->
      <!-- 10.4 1ヶ月ごとの表示切り替え機能を作ろう -->
      <td>【<%= l(@first_day, format: :middle) %>】勤怠管理表</td>
      <!-- 9.2.2 バリデーション設定に伴う表示に対応 /9.2.3 基本表示用ヘルパーを作る-->
      <td>指定勤務時間：<%-format_basic_info(@user.work_time) %></td>
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <!-- ##10.3 "ユーザー"の月日を一覧表示 -->
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>出勤日数</td>
      <!-- ##10.3 "ユーザー"の月日を一覧表示 -->
      <td>月末日：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<!-- 10.4 1ヶ月ごとの表示切り替え機能を作ろう -->
<div class="btn-users-show">
  <%= link_to "⇦ 前月へ", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
  <%= link_to "翌月へ ⇨", user_path(date: @first_day.next_month), class: "btn btn-info" %>
</div>

<!-- 10.2 月日の表示 -->
<!-- 10.3 "ユーザー"の月日を一覧表示：構文の削除 -->
<!-- 10.4 1ヶ月ごとの表示切り替え機能を作ろう：構文の復活 -->
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>勤怠登録</th>
        <th>出勤時間</th>
        <th>退勤時間</th>
        <th>在社時間</th>
        <th>備考</th>
      </tr>
    </thead>
    
    <tbody>
      <!-- 10.2.1 月日の表示 -->
      <!-- 10.3 "ユーザー"の月日を一覧表示 -->
      <!-- <% (@first_day..@last_day).each do |day| %> -->
      <% @attendances.each do |day| %>
    　　<tr>
    　  　  <!--10.2.2 月日の表示 -->
    　　    <!-- <td><%= l(day, format: :short) %></td> -->
          <!-- 10.2.3 月の初日と末日の表示 -->
          <td><%= l(day.worked_on, format: :short) %></td>
          <!-- 10.2.2 月日の表示 -->
      　　<!-- <td><%= $days_of_the_week[day.wday] %></td> -->
      　　<!-- 10.2.3 月の初日と末日の表示 -->
      　　<td><%= $days_of_the_week[day.worked_on.wday] %></td>
      　　<td></td>
      　　<td></td>
      　　<td></td>
      　　<td></td>
      　　<td></td>
    　　</tr>
    　<% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.10-6未完成.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <!-- 10.2 月日の一覧表示 -->
      <!--  <td>時間管理表</td> -->
      <!-- 10.4 1ヶ月ごとの表示切り替え機能を作ろう -->
      <td>【<%= l(@first_day, format: :middle) %>】勤怠管理表</td>
      <!-- 9.2.2 バリデーション設定に伴う表示に対応 /9.2.3 基本表示用ヘルパーを作る-->
      <td>指定勤務時間：<%=format_basic_info(@user.work_time) %></td>
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <!-- ##10.3 "ユーザー"の月日を一覧表示 -->
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>出勤日数</td>
      <!-- ##10.3 "ユーザー"の月日を一覧表示 -->
      <td>月末日：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<!-- 10.4 1ヶ月ごとの表示切り替え機能を作ろう -->
<div class="btn-users-show">
  <%= link_to "⇦ 前月へ", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
  <%= link_to "翌月へ ⇨", user_path(date: @first_day.next_month), class: "btn btn-info" %>
</div>

<!-- 10.2 月日の表示 -->
<!-- 10.3 "ユーザー"の月日を一覧表示：構文の削除 -->
<!-- 10.4 1ヶ月ごとの表示切り替え機能を作ろう：構文の復活 -->
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>勤怠登録</th>
        <th>出勤時間</th>
        <th>退勤時間</th>
        <th>在社時間</th>
        <th>備考</th>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <!-- 10.2.3 月の初日と末日の表示 -->
          <td><%= l(day.worked_on, format: :short) %></td>
          <!-- 10.2.3 月の初日と末日の表示 -->
      　　<td><%= $days_of_the_week[day.worked_on.wday] %></td>
      　　<td>
      　　    <!-- 10.6.1 退勤ボタンを表示/退勤登録ボタン -->
      　　    <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
      　　</td>
      　　<!-- 5.3-3 出勤登録アクションを作る/出勤登録ボタン -->
      　　<td><%= l(day.started_at, format: :time) if day.started_at.present? %></td>
      　　<!-- 10.6.2 updateアクションを完成/退勤登録ボタン -->
      　　<td><%= l(day.finished_at, format: :time) if day.finished_at.present? %></td>
      　　<td></td>
      　　<td></td>
    　　</tr>
    　<% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <!-- 10.2 月日の一覧表示 -->
      <!--  <td>時間管理表</td> -->
      <!-- 10.4 1ヶ月ごとの表示切り替え機能を作ろう -->
      <td>【<%= l(@first_day, format: :middle) %>】勤怠管理表</td>
      <!-- 9.2.2 バリデーション設定に伴う表示に対応 /9.2.3 基本表示用ヘルパーを作る-->
      <td>指定勤務時間：<%=format_basic_info(@user.work_time) %></td>
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <!-- ##10.3 "ユーザー"の月日を一覧表示 -->
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <!-- 10.7.1 出勤日数を表示 -->
      <td>出勤日数：<%= @worked_sum %>日</td>
      <!-- ##10.3 "ユーザー"の月日を一覧表示 -->
      <td>月末日：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<!-- 10.4 1ヶ月ごとの表示切り替え機能を作ろう -->
<div class="btn-users-show">
  <%= link_to "⇦ 前月へ", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
  <!-- 11.1.3-1 勤怠情報ページのボタン作成 -->
  <%= link_to "1ヶ月の勤怠編集へ", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-success" %>
  <%= link_to "翌月へ ⇨", user_path(date: @first_day.next_month), class: "btn btn-info" %>
</div>

<!-- 10.2 月日の表示 -->
<!-- 10.3 "ユーザー"の月日を一覧表示：構文の削除 -->
<!-- 10.4 1ヶ月ごとの表示切り替え機能を作ろう：構文の復活 -->
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>勤怠登録</th>
        <th>出勤時間</th>
        <th>退勤時間</th>
        <th>在社時間</th>
        <th>備考</th>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <!-- 10.2.3 月の初日と末日の表示 -->
          <td><%= l(day.worked_on, format: :short) %></td>
          <!-- 10.2.3 月の初日と末日の表示 -->
      　　<td><%= $days_of_the_week[day.worked_on.wday] %></td>
      　　<td>
      　　    <!-- 10.6.1 退勤ボタンを表示/退勤登録ボタン -->
      　　    <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
      　　</td>
      　　<!-- 5.3-3 出勤登録アクションを作る/出勤登録ボタン -->
      　　<td><%= l(day.started_at, format: :time) if day.started_at.present? %></td>
      　　<!-- 10.6.2 updateアクションを完成/退勤登録ボタン -->
      　　<td><%= l(day.finished_at, format: :time) if day.finished_at.present? %></td>
      　　<td>
            <!-- 10.8 在社時間を計算 -->
            <% if day.started_at.present? && day.finished_at.present? %>
             <!-- 10.9.2 累計在社時間の計算/ 勤怠表を仕上げ -->
             <%= str_times = working_times(day.started_at, day.finished_at) %>
             <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
      　　</td>
      　　<!--  11.3.2-2 note（備考）の情報をユーザー勤怠情報ページで表示 -->
      　　<td><%= day.note %></td>
    　　</tr>
    　<% end %>
    </tbody>
    
    <!-- 10.9 勤怠表を仕上げ -->
    <tfoot>
      <!--rouspan:縦結合、colspan:横結合-->
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="2">総合勤務時間</td>
        <td colspan="2">累計在社時間</td>
        <td colspan="2"></td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <!-- 10.9.1 総合勤務時間の計算/ 勤怠表を仕上げ -->
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <!-- 10.9.2 累計在社時間の計算/ 勤怠表を仕上げ -->
        <td colspan="2"><%= format("%.2f", @total_workingtimes.to_f) %></td>
      </tr>
    </tfoot>
  </table>
</div>