config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'

  ##get 'static_pages/top'
  root 'static_pages#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  
  ## ログイン機能(6.1 最初に実装するnewアクションを指定して生成)
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  ## 9.3.1 モーダルウインドウを表示  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      ## 11.1 勤怠編集ページの作成し、ルーティングを設定
      get 'attendances/edit_one_month'
      ## 11.1.4 勤怠編集ページの更新ボタン作成
      patch 'attendances/update_one_month'
    end
    ##10.5.1 ルーティングを設定/出勤登録ボタン
    resources :attendances, only: :update
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  ##10.1.2 バリデーションを設定(勤怠情報表示ページ)
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  ##10.1.3 カスタムメソッドを作ろう(勤怠情報表示ページ)
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  
  ## 11.3 繰り返し更新処理を実装
  validate :started_at_than_finished_at_fast_if_invalid

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  ## 11.3 繰り返し更新処理を実装
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より速い退勤時間は無効です") if started_at > finished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  ## 11.1.3 勤怠情報ページのアクション作成でset_userアクションをapplicationコントローラーへ引越し、beforeフィルターの設定
  before_action :set_user, only: [:edit_one_month, :update_one_month]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  ## 11.3.4 認可機能を追加
  before_action admin_or_correct_user, only: [update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: :edit_one_month
  
  ##<!-- 10.6.2 updateアクションを完成/退勤登録ボタン -->
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  ##10.5.3 出勤登録アクションを作る/出勤登録ボタン
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      ##10.5.3-2 出勤登録アクションを作る/出勤登録ボタン
      ##if @attendance.update_attributes(started_at: Time.current)
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        ##flash[:danger] = "勤怠登録に失敗しました。やり直してください。"
        ##<!-- 10.6.2 updateアクションを完成/退勤登録ボタン -->
        flash[:danger] = UPDATE_ERROR_MSG
      end
    ##<!-- 10.6.2 updateアクションを完成/退勤登録ボタン -->
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  ## 11.1.3 勤怠編集ページのアクション作成
  def edi_one_month 
  end
  
  ## 11.1.4 勤怠編集ページの更新アクション作成
  def update_one_month
    ## 11.3.2 例外処理を含めた更新を追加
     # トランザクションを開始します。
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
      end
    end
    ## 11.3.2-2 例外処理を含めた更新を追加
    flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
    redirect_to user_url(date: params[:date])
   # トランザクションによるエラーの分岐です。
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  ## 11.2 StrongParametersの応用
  private
    # 1ヶ月分の勤怠情報を扱います。
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
  
  ## 11.3.4 認可機能を追加
  # 管理権限者、または現在ログインしているユーザーを許可します。
  def admin_or_correct_user
    @user = User.find(params[:user_id]) if @user.blank?
    unless current_user?(@user) || current_user.admin?
      flash[danger] = "編集権限がありません。"
      redirect_to(root_url)
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  ##10.6.1 退勤ボタンを表示/退勤登録ボタン
  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end
  ##<!-- 10.8 在社時間を計算 -->
  def working_times(start, finish)
    format("%.2f", (((finish - start ) / 60 ) / 60.0))
  end
end

app/views/attendances/edit_one_month.html.erb
<!-- ## 11.1.2 勤怠編集ページのビュー作成 -->
<% provide(:title, @user.name) %>
<!-- 11.1.5 勤怠編集ページの更新ボタン作成 -->
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances" >
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出勤時間</th>
          <th>退勤時間</th>
          <th>在社時間</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <!-- 11.1.6 勤怠編集ページのfields_forヘルパーメソッド作成 -->
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td><%= $days_of_the_week[day.worked_on.wday] %></td>
              <!-- 3 フォームの入力を制限 -->
              <% if !current_user.admin? && (Date.current < day.worked_on) %>
                <!-- 11.1.6 勤怠編集ページのfields_forヘルパーメソッド作成 -->
                <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
                <!-- 11.1.6 勤怠編集ページのfields_forヘルパーメソッド作成 -->
                <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :started_at, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
              <% end %>
              <!-- 11.1.6 勤怠編集ページのfields_forヘルパーメソッド作成 -->
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at) %>
                <% end %>
              </td>
              <!-- 11.1.6 勤怠編集ページのfields_forヘルパーメソッド作成 -->
              <td><%= attendance.text_field :note, class: "form-control" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <!-- 11.1.4 勤怠編集ページのキャンセルボタン作成 -->
  <dir class="center">
  <!-- 11.1.5 勤怠編集ページの更新ボタン作成 -->
    <%= f.submit "まとめて更新", class: "btn btn-lg btn-primary" %>
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
  </dir>
<% end %>