config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'

  ##get 'static_pages/top'
  root 'static_pages#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  
  ## ログイン機能(6.1 最初に実装するnewアクションを指定して生成)
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  ## 9.3.1 モーダルウインドウを表示  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      ## 11.1 勤怠編集ページの作成し、ルーティングを設定
      get 'attendances/edit_one_month'
      ## 11.1.4 勤怠編集ページの更新ボタン作成
      patch 'attendances/update_one_month'
    end
    ##10.5.1 ルーティングを設定/出勤登録ボタン
    resources :attendances, only: :update
  end
end

app/views/layouts/_header.html.1.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <!-- 3.4 リンクを設定 -->
    <!-- <%= link_to "Attendance App", '#', id: "logo" %> -->
    <%= link_to "Attendance App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <!-- 3.4 リンクを設定 -->
        <!-- <li><%= link_to "Top",   '#' %></li> -->
        <li><%= link_to "Top", root_path %></li>
        <!-- 6.4 レイアウトのログイン＆ログアウト仕様に対応 -->
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Show", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
        <!-- 6.2.1 ログインページへのリンクも設定 -->
        <!-- <li><%= link_to "Log in", '#' %></li> -->
        <li><%= link_to "Log in", login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Attendance App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><%= link_to "Top", root_path %></li> -->
        <!-- 8x.8 ヘッダーリンクなどViewにおいて直接修正 -->
        <li><%=link_to "ホーム",root_path %></li>
        <% if logged_in? %>
          <!-- 8.4 全てのユーザーを表示するページ -->
          <!-- <li><%= link_to "Users", '#' %></li> -->
          <!-- <li><%= link_to "users", users_path %></li> -->
          <!-- 8x.8 ヘッダーリンクなどViewにおいて直接修正 -->
          <li><%= link_to "全てのユーザー", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              メニュー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <!-- <li><%= link_to "Show", current_user %></li> -->
              <!-- 8x.8 ヘッダーリンクなどViewにおいて直接修正 -->
              <li><%= link_to "勤怠", current_user %>
              <!-- <li><%= link_to "Settings", edit_user_path(current_user) %></li> -->
              <!-- 8x.8 ヘッダーリンクなどViewにおいて直接修正 -->
              <li><%= link_to "設定", edit_user_path(current_user) %>
              <li class="divider"></li>
              <li>
                <!-- <%= link_to "Log out", logout_path, method: :delete %> -->
                <!-- 8x.8 ヘッダーリンクなどViewにおいて直接修正 -->
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <!-- <li><%= link_to "Log in", login_path %></li> -->
          <!-- 8x.8 ヘッダーリンクなどViewにおいて直接修正 -->
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> | AttendanceApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <!-- 3.3 パーシャルを使おう.HTML shimがこの1行で収まる -->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <!-- <header class="navbar navbar-fixed-top navbar-inverse"> -->
      <!-- <div class="container">
       <!-- <%= link_to "Attendance App", '#', id: "logo" %> -->
       <!--  <nav> -->
          <!-- <ul class="nav navbar-nav navbar-right"> -->
            <!-- <li><%= link_to "Top",   '#' %></li> -->
            <!-- <li><%= link_to "Log in", '#' %></li> -->
          <!-- </ul> -->
        <!-- </nav> -->
      <!-- </div> -->
    <!-- </header> -->
    <!-- 3.3 パーシャルを使おう.headerの内容がこの1行で収まる -->
    <%= render 'layouts/header' %>
    <div class="container">
      <!-- 5.5.6 サクセスメッセージを表示 -->
      <% flash.each do |message_type, msg| %>
      <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <!-- 5.1 レイアウトにデバッグ情報を追加 -->
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>